### ISSUE TITLE
The test, how to drag title to move around

### ISSUE THREAD

**Issue by ericxin1982** [ivteplo/html-sheet-element#12]
Sorry,

This supports drag title to move around?
If yes, how to?

Thanks
Eric Xin

**Comment by ivteplo** [comment]
Hello Eric,

Thank you for the interest in this project! Dragging the title of a sheet is currently not supported due to the implementation approach. This seems to be more of a functionality that a window component would have to implement.

I hope you will find a library that fulfills your requirements.

Best wishes,
Ivan Teplov
